import Nav from './components/Nav'
import SideBar from './components/SideBar'

import '@/styles/global.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SideBar />
        <main>
          <div className='navbar'>
            <Nav />
          </div>
          <div className='render'>
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
